### ISSUE TITLE
Giá tiền sản phẩm

### ISSUE THREAD

**Issue by AndrewNguyen27296** [XinKaChu/ShoeShop#3]
Giá tiền sản phẩm được tính theo USD , VND hay là cả hai ?

**Comment by grazerjink** [comment]
Thống nhất một kiểu tiền tề thôi, đa ngôn ngữ là ổn, tiền tệ ko đổi thành USD, vẫn đề là VND, kí tự quốc tế rồi

**Comment by grazerjink** [comment]
Thống nhất một kiểu tiền tề thôi, đa ngôn ngữ là ổn, tiền tệ ko đổi thành USD, vẫn đề là VND, kí tự quốc tế rồi
